# Generated by Django 4.0.1 on 2022-01-24 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_checkout'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('products', models.CharField(max_length=200)),
                ('paymentmethod', models.CharField(max_length=100)),
            ],
        ),
    ]
