# Generated by Django 4.0.1 on 2022-01-24 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_orders_checkout'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='payment',
            new_name='payment_method',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='product',
            new_name='products',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='user',
            new_name='username',
        ),
    ]
