# Generated by Django 4.0.1 on 2022-01-24 03:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0003_rename_payment_orders_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='products',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.products'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
