# Generated by Django 4.0.1 on 2022-01-24 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_orders_products_alter_orders_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='products',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='orders',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
